CREATE TABLE [dbo].[RateTable] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Action]      VARCHAR (250)  NULL,
    [Duration]    DECIMAL (3, 2) NULL,
    [ADAMS]       DECIMAL (8, 4) NULL,
    [ALAMOSA]     DECIMAL (8, 4) NULL,
    [ARAPAHOE]    DECIMAL (8, 4) NULL,
    [ARCHULETA]   DECIMAL (8, 4) NULL,
    [BACA]        DECIMAL (8, 4) NULL,
    [BENT]        DECIMAL (8, 4) NULL,
    [BOULDER]     DECIMAL (8, 4) NULL,
    [BROOMFIELD]  DECIMAL (8, 4) NULL,
    [CHAFFEE]     DECIMAL (8, 4) NULL,
    [CHEYENNE]    DECIMAL (8, 4) NULL,
    [CLEAR CREEK] DECIMAL (8, 4) NULL,
    [CONEJOS]     DECIMAL (8, 4) NULL,
    [COSTILLA]    DECIMAL (8, 4) NULL,
    [CROWLEY]     DECIMAL (8, 4) NULL,
    [CUSTER]      DECIMAL (8, 4) NULL,
    [DELTA]       DECIMAL (8, 4) NULL,
    [DENVER]      DECIMAL (8, 4) NULL,
    [DOLORES]     DECIMAL (8, 4) NULL,
    [DOUGLAS]     DECIMAL (8, 4) NULL,
    [EAGLE]       DECIMAL (8, 4) NULL,
    [EL PASO]     DECIMAL (8, 4) NULL,
    [ELBERT]      DECIMAL (8, 4) NULL,
    [FREMONT]     DECIMAL (8, 4) NULL,
    [GARFIELD]    DECIMAL (8, 4) NULL,
    [GILPIN]      DECIMAL (8, 4) NULL,
    [GRAND]       DECIMAL (8, 4) NULL,
    [GUNNISON]    DECIMAL (8, 4) NULL,
    [HINSDALE]    DECIMAL (8, 4) NULL,
    [HUERFANO]    DECIMAL (8, 4) NULL,
    [JACKSON]     DECIMAL (8, 4) NULL,
    [JEFFERSON]   DECIMAL (8, 4) NULL,
    [KIOWA]       DECIMAL (8, 4) NULL,
    [KIT CARSON]  DECIMAL (8, 4) NULL,
    [LA PLATA]    DECIMAL (8, 4) NULL,
    [LAKE]        DECIMAL (8, 4) NULL,
    [LARIMER]     DECIMAL (8, 4) NULL,
    [LAS ANIMAS]  DECIMAL (8, 4) NULL,
    [LINCOLN]     DECIMAL (8, 4) NULL,
    [LOGAN]       DECIMAL (8, 4) NULL,
    [MESA]        DECIMAL (8, 4) NULL,
    [MINERAL]     DECIMAL (8, 4) NULL,
    [MOFFAT]      DECIMAL (8, 4) NULL,
    [MONTEZUMA]   DECIMAL (8, 4) NULL,
    [MONTROSE]    DECIMAL (8, 4) NULL,
    [MORGAN]      DECIMAL (8, 4) NULL,
    [OTERO]       DECIMAL (8, 4) NULL,
    [OURAY]       DECIMAL (8, 4) NULL,
    [PARK]        DECIMAL (8, 4) NULL,
    [PHILLIPS]    DECIMAL (8, 4) NULL,
    [PITKIN]      DECIMAL (8, 4) NULL,
    [PROWERS]     DECIMAL (8, 4) NULL,
    [PUEBLO]      DECIMAL (8, 4) NULL,
    [RIO BLANCO]  DECIMAL (8, 4) NULL,
    [RIO GRANDE]  DECIMAL (8, 4) NULL,
    [ROUTT]       DECIMAL (8, 4) NULL,
    [SAGUACHE]    DECIMAL (8, 4) NULL,
    [SAN JUAN]    DECIMAL (8, 4) NULL,
    [SAN MIGUEL]  DECIMAL (8, 4) NULL,
    [SEDGWICK]    DECIMAL (8, 4) NULL,
    [SUMMIT]      DECIMAL (8, 4) NULL,
    [TELLER]      DECIMAL (8, 4) NULL,
    [WASHINGTON]  DECIMAL (8, 4) NULL,
    [WELD]        DECIMAL (8, 4) NULL,
    [YUMA]        DECIMAL (8, 4) NULL,
    CONSTRAINT [PK__RateTabl__3214EC076D96C06B] PRIMARY KEY CLUSTERED ([Id] ASC)
);

